{% set name = "readwritememory" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ReadWriteMemory-{{ version }}.tar.gz
  sha256: 6a194074dc760809db03ec744bbd1e0eec649c32d016400c0ae7b32cf649d08d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.4
    - pip
  run:
    - python >=3.4

test:
  imports:
    - ReadWriteMemory
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/vsantiago113/ReadWriteMemory
  summary: ReadWriteMemory Class to work with Windows process memory and hacking video games.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
